### PR TITLE
update GALAXY_PLATFORMS dictionary

### PR DESCRIPTION
**Pull request by ziegenberg**
- add Ubuntu Jammy Jellyfish
- add Solaris 11.4
- add vCenter 7.0 and vSphere 7.0 to GALAXY_PLATFORMS 
- add Windows Server 2022
- add Synology DSM 6.0, 6.1, 6.2 and 7.0
- add SLES 12SP2, 12SP3, 12SP4, 12SP5, 15SP1, 15SP2 and 15SP3
- add OpenBSD 6.8, 6.9 and 7.0
- add macOS Catalina, Mojave and Monterey
- add FreeBSD 11.4, 12.2 and 13.0

### CODE REVIEW

**Comment by ssbarnea** [comment]
@ziegenberg The python file is generated to human written. Search for dump_galaxy_platforms --- That is not the correct way to refresh it.

I am not against changing the way to generate it and even making it black compatible but we cannot switch to a new way in a single change.

Lets first update it using old method and look to improve it later, so our changes are traceable.

**Review by ssbarnea — CHANGES_REQUESTED** [review]
Needs different approach

**Comment by ziegenberg** [comment]
Hi @ssbarnea,
do you want this to be three different PR? Or are three commits in one PR sufficient?

1. update GALAXY_PLATFORMS via dump_galaxy_platforms
2. change format of GALAXY_PLATFORMS to be `black` compatible
3. add more platforms

**Comment by ziegenberg** [comment]
I rebased onto current `main`, because 83b36ee2102243464efdb2031311da938b832beb introtuced changes to `f/ansible-meta.json`.

I also added 5889f85183bff83ac11d1832ed75e16165f73de6 for updating the platforms dumped from the API.

**Comment by ssbarnea** [comment]
@ziegenberg If you could do them separately it would awesome. Just use the commented method to dump them again and make a PR that is refreshing the two files. That should fix initial issue and give us more time to improve the process after.

**Comment by ziegenberg** [comment]
gimme a few seconds and there'll be a new PR.

**Comment by ziegenberg** [comment]
See #102 for the PR on updating the platforms dumped from the API.

**Comment by ziegenberg** [comment]
See #103 for the PR on introducing `black` compatible formatting of `GALAXY_PLATFORMS`.

I will rebase this PR once #103 is merged because I expect more merge conflicts when I rebase just now.

**Comment by ziegenberg** [comment]
Hi @ssbarnea 

I rebased and also fixed a small error I made in the #103 dumping the platforms all the time. There's now #104 making dumping the platforms configurable.

This is now ready for review.

**Pull request merged**
